enum OnboardingCatalog {
    static let models: [OnboardingModel] = [
        .init(id: "tiny",     family: "Whisper",  label: "Tiny",
              displaySize: "39 MB",
              wer: "12.4%", speed: "Realtime · 8×",
              body: "Drafts, chat, casual notes. Stumbles on names and accents.",
              recommended: false,
              engine: .whisper, realID: "openai_whisper-tiny"),
        .init(id: "small",    family: "Whisper",  label: "Small",
              displaySize: "244 MB",
              wer: "7.1%", speed: "Realtime · 4×",
              body: "The sweet spot. Handles German + English mid-sentence switches.",
              recommended: true,
              engine: .whisper, realID: "openai_whisper-small"),
        .init(id: "large",    family: "Whisper",  label: "Large",
              displaySize: "947 MB",
              wer: "4.3%", speed: "Realtime · 1.2×",
              body: "Long-form editorial, jargon, multilingual. Needs Apple Silicon.",
              recommended: false,
              engine: .whisper, realID: "openai_whisper-large-v3_947MB"),
        .init(id: "parakeet", family: "Parakeet", label: "TDT v3",
              displaySize: "1.1 GB",
              wer: "5.2%", speed: "Realtime · 10×",
              body: "NVIDIA's blistering ASR — fastest of the lot, English-first, surprisingly accurate.",
              recommended: false,
              engine: .parakeet, realID: "v3"),
    ]

    static let brains: [OnboardingBrain] = [
        .init(id: "llama8b", name: "Llama 3.1", variant: "8B",
              family: "Meta · open weights", size: "4.9 GB", context: "128k",
              speed: "Fast", quality: 86,
              body: "A solid local workhorse. Translates well, cleans up rambling, expands snippets.",
              recommended: true),
        .init(id: "mistral7b", name: "Mistral", variant: "7B",
              family: "Mistral · open", size: "4.1 GB", context: "32k",
              speed: "Realtime", quality: 82,
              body: "Lean and very fast. Excellent for short tasks like translation and punctuation fixes.",
              recommended: false),
        .init(id: "qwen14b", name: "Qwen 2.5", variant: "14B",
              family: "Alibaba · open", size: "8.7 GB", context: "128k",
              speed: "Medium", quality: 91,
              body: "Heavier and more thoughtful. Multilingual translation is its real strength.",
              recommended: false),
        .init(id: "phi35", name: "Phi-3.5", variant: "Mini",
              family: "Microsoft · open", size: "2.3 GB", context: "128k",
              speed: "Realtime", quality: 78,
              body: "A 3.8B model that punches above its weight. Wonderful when battery matters.",
              recommended: false),
    ]
}
