enum OnboardingCatalog {
    static let models: [OnboardingModel] = [
        .init(id: "tiny",
              displaySize: "39 MB",
              wer: "12.4%", speed: "Realtime · 8×",
              body: "Drafts, chat, casual notes. Stumbles on names and accents.",
              recommended: false,
              engine: .whisper, realID: "openai_whisper-tiny"),
        .init(id: "small",
              displaySize: "244 MB",
              wer: "7.1%", speed: "Realtime · 4×",
              body: "The sweet spot. Handles German + English mid-sentence switches.",
              recommended: false,
              engine: .whisper, realID: "openai_whisper-small"),
        .init(id: "large",
              displaySize: "947 MB",
              wer: "4.3%", speed: "Realtime · 1.2×",
              body: "Long-form editorial, jargon, multilingual. Needs Apple Silicon.",
              recommended: false,
              engine: .whisper, realID: "openai_whisper-large-v3_947MB"),
        .init(id: "parakeet",
              displaySize: "1.1 GB",
              wer: "5.2%", speed: "Realtime · 10×",
              body: "Blistering streaming ASR — fastest of the lot, English-first, surprisingly accurate.",
              recommended: true,
              engine: .parakeet, realID: "v3"),
    ]

    static let brains: [OnboardingBrain] = [
        .init(id: "gemma2b",
              size: "1.4 GB", context: "8k",
              speed: "Realtime", quality: 78,
              body: "Lightweight default. Strong at translation and tidy-ups, easy on disk and battery.",
              recommended: true,
              registryKey: "gemma4_e2b_it_4bit"),
        .init(id: "gemma4b",
              size: "2.7 GB", context: "8k",
              speed: "Fast", quality: 83,
              body: "Bigger sibling of Quill. Noticeably better tone and rewriting at modest cost.",
              recommended: false,
              registryKey: "gemma4_e4b_it_4bit"),
        .init(id: "qwen",
              size: "4.4 GB", context: "128k",
              speed: "Medium", quality: 88,
              body: "Multilingual translation is its real strength. Larger context for longer passages.",
              recommended: false,
              registryKey: "qwen2_5_7b"),
    ]
}
